### ISSUE TITLE
Enemies spawn

### ISSUE THREAD

**Issue by Kaslacrout** [Hpn4/DungeonCrawler#1]
Sometimes enemies appears in walls or in pits, so we can't fight them 😞.
![image1](https://github.com/Hpn4/DungeonCrawler/assets/90468509/d2a7b925-45d7-4451-a7f7-ecfe045cb01a)

**Comment by Hpn4** [comment]
It was a project that I made many years ago, so there are a lot of bugs 🥲 . I don't know if I will maintain it.
But anyway, the issue is fixed.
