### ISSUE TITLE
Touching walls is dangerous

### ISSUE THREAD

**Issue by Kaslacrout** [Hpn4/DungeonCrawler#2]
When we hit a wall, we get stuck.
![image2](https://github.com/Hpn4/DungeonCrawler/assets/90468509/f780a227-e774-4658-93a7-0f99e8d0d82d)

**Comment by Hpn4** [comment]
It was a project that I made many years ago, so there are a lot of bugs 🥲 . I don't know if I will maintain it.
But anyway, the issue is fixed.

**Comment by Kaslacrout** [comment]
Wow, so reactive 😁
